spring:
  datasource:
    url: jdbc:mysql://localhost:3306/min?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update  # (none, validate, update, create, create-drop ? ??)
    properties:
      hibernate:
        format_sql: true  # SQL? ?? ?? ??
        show_sql: true    # ??? SQL ??
